AppTop := /usr/local/share/polymake
ExtensionTop := /home/cecilia/Escritorio/Sandbox/discrete-geometry-lectures-Cgiron/2013/coding/dag2013-cecilia
BuildDir := ../..
ProjectTop := /usr/local/share/polymake
include ${ProjectTop}/support/build.make
